apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: a2e01fd50cf9711e8b9fa066499c34bb-105882575.eu-west-1.elb.amazonaws.com
      http:
        paths:
        - path: /test
          backend:
            serviceName: source-ip
            servicePort: 80
